DROP TABLE IF EXISTS attachment CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS "section" CASCADE;
DROP TABLE IF EXISTS topic CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TYPE IF EXISTS permissions_type;
DROP TYPE IF EXISTS status_type;
