package forum;
// Generated 26.02.2020 21:11:41 by Hibernate Tools 5.4.7.Final

/**
 * AttachmentId generated by hbm2java
 */
public class AttachmentId implements java.io.Serializable {

	private int postId;
	private String fileLink;

	public AttachmentId() {
	}

	public AttachmentId(int postId, String fileLink) {
		this.postId = postId;
		this.fileLink = fileLink;
	}

	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public String getFileLink() {
		return this.fileLink;
	}

	public void setFileLink(String fileLink) {
		this.fileLink = fileLink;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttachmentId))
			return false;
		AttachmentId castOther = (AttachmentId) other;

		return (this.getPostId() == castOther.getPostId())
				&& ((this.getFileLink() == castOther.getFileLink()) || (this.getFileLink() != null
						&& castOther.getFileLink() != null && this.getFileLink().equals(castOther.getFileLink())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPostId();
		result = 37 * result + (getFileLink() == null ? 0 : this.getFileLink().hashCode());
		return result;
	}

}
