package forum;
// Generated 26.02.2020 21:11:41 by Hibernate Tools 5.4.7.Final

/**
 * Attachment generated by hbm2java
 */
public class Attachment implements java.io.Serializable {

	private AttachmentId id;

	public Attachment() {
	}

	public Attachment(AttachmentId id) {
		this.id = id;
	}

	public AttachmentId getId() {
		return this.id;
	}

	public void setId(AttachmentId id) {
		this.id = id;
	}

}
