package forum;
// Generated 26.02.2020 21:11:41 by Hibernate Tools 5.4.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {
	
	private static final long serialVersionUID = 3477267745021312717L;
	private int postId;
	private Topic topic;
	private User user;
	private String text;
	private Timestamp datetime;
	@SuppressWarnings("rawtypes")
	private Set attachments = new HashSet(0);
	
	public Post() {
		
	}
	
	public Post(Topic topic, User user, String text, Timestamp datetime) {
		this.topic = topic;
		this.user = user;
		this.text = text;
		this.datetime = datetime;
	}

	public Post(int postId, Topic topic, User user, String text, Timestamp datetime) {
		this.postId = postId;
		this.topic = topic;
		this.user = user;
		this.text = text;
		this.datetime = datetime;
	}

	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Timestamp getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Timestamp datetime) {
		this.datetime = datetime;
	}
	
	@SuppressWarnings("rawtypes")
	public Set getAttachments() {
		return this.attachments;
	}

	@SuppressWarnings("rawtypes")
	public void setAttachments(Set attachments) {
		this.attachments = attachments;
	}
	
	public void addAttachment(Attachment at) {
		this.attachments.add(at);
		at.setPost(this);
	}

	@Override
	public String toString() {
		return "Post [postId=" + postId + ", topic=" + topic + ", user=" + user + ", text=" + text + ", datetime="
				+ datetime + ", attachments=" + attachments + "]";
	}

}
