package forum;
// Generated 26.02.2020 21:11:41 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5794988324661525799L;
	private int userId;
	private String login;
	private byte[] password;
	private Date dateOfRegistration;
	private String permissions;
	private String status;
	private Set posts = new HashSet(0);

	public User() {
	}

	public User(int userId, String login, byte[] password, Date dateOfRegistration, String permissions, String status) {
		this.userId = userId;
		this.login = login;
		this.password = password;
		this.dateOfRegistration = dateOfRegistration;
		this.permissions = permissions;
		this.status = status;
	}

	public User(int userId, String login, byte[] password, Date dateOfRegistration, String permissions, String status,
			Set posts) {
		this.userId = userId;
		this.login = login;
		this.password = password;
		this.dateOfRegistration = dateOfRegistration;
		this.permissions = permissions;
		this.status = status;
		this.posts = posts;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

	public Date getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(Date dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	public String getPermissions() {
		return this.permissions;
	}

	public void setPermissions(String permissions) {
		this.permissions = permissions;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

}
